version: '3.8'

services:
  web:
    build: .
    container_name: project6-container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000

    command: python app.py

  mongo:
    image: mongo:6.0
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
